{{ config(materialized='view') }}

select
    STORE::INT as STORE_ID,
    DATE::DATE as STORE_DATE,
    FUEL_PRICE::DECIMAL(10,3) as FUEL_PRICE,
    TEMPERATURE::DECIMAL(10,2) as STORE_TEMPERATURE,
    UNEMPLOYMENT::DECIMAL(10,4) as UNEMPLOYEMENT,
    CPI::DECIMAL(18,4) as CPI,
    MARKDOWN1::DECIMAL(18,2) as MARKDOWN1,
    MARKDOWN2::DECIMAL(18,2) as MARKDOWN2,
    MARKDOWN3::DECIMAL(18,2) as MARKDOWN3,
    MARKDOWN4::DECIMAL(18,2) as MARKDOWN4,
    MARKDOWN5::DECIMAL(18,2) as MARKDOWN5,
    ISHOLIDAY::VARCHAR as ISHOLIDAY
from {{ source('BRONZE', 'RAW_MACRO_DATA') }}
