COPY INTO WALMART_DB.BRONZE.RAW_SALES
FROM @WALMART_DB.BRONZE.WALMART_STAGE/department.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT)
FORCE = TRUE;

COPY INTO WALMART_DB.BRONZE.RAW_STORES
FROM @WALMART_DB.BRONZE.WALMART_STAGE/stores.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT)
FORCE = TRUE;

COPY INTO WALMART_DB.BRONZE.RAW_MACRO_DATA
FROM @WALMART_DB.BRONZE.WALMART_STAGE/fact.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT)
FORCE = TRUE;
