CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_SALES (
    STORE INT,
    DEPT INT,
    DATE DATE,
    WEEKLY_SALES FLOAT,
    ISHOLIDAY BOOLEAN
);

CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_MACRO_DATA (
    STORE INT,
    DATE DATE,
    TEMPERATURE FLOAT,
    FUEL_PRICE FLOAT,
    MARKDOWN1 FLOAT,
    MARKDOWN2 FLOAT,
    MARKDOWN3 FLOAT,
    MARKDOWN4 FLOAT,
    MARKDOWN5 FLOAT,
    CPI FLOAT,
    UNEMPLOYMENT FLOAT,
    ISHOLIDAY BOOLEAN
);

CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_STORES (
    STORE INT,
    TYPE STRING,
    SIZE INT
);
