USE ROLE ACCOUNTADMIN;

USE WAREHOUSE COMPUTE_WH;

CREATE OR REPLACE DATABASE WALMART_DB;

CREATE SCHEMA IF NOT EXISTS WALMART_DB.BRONZE;

CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_SALES (
    STORE INT,
    DEPT INT,
    DATE DATE,
    WEEKLY_SALES FLOAT,
    ISHOLIDAY BOOLEAN
);

CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_MACRO_DATA (
    STORE INT,
    DATE DATE,
    TEMPERATURE FLOAT,
    FUEL_PRICE FLOAT,
    MARKDOWN1 FLOAT,
    MARKDOWN2 FLOAT,
    MARKDOWN3 FLOAT,
    MARKDOWN4 FLOAT,
    MARKDOWN5 FLOAT,
    CPI FLOAT,
    UNEMPLOYMENT FLOAT,
    ISHOLIDAY BOOLEAN
);

CREATE OR REPLACE TABLE WALMART_DB.BRONZE.RAW_STORES (
    STORE INT,
    TYPE STRING,
    SIZE INT
);

CREATE OR REPLACE FILE FORMAT WALMART_DB.BRONZE.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '');

CREATE OR REPLACE STAGE WALMART_DB.BRONZE.WALMART_STAGE
URL = 's3://anthonyamabile-walmart-raw'
CREDENTIALS = (
  AWS_KEY_ID = '<YOUR_AWS_KEY_ID>'
  AWS_SECRET_KEY = '<AWS_SECRET_KEY>'
)
FILE_FORMAT = WALMART_DB.BRONZE.CSV_FORMAT;

SHOW STAGES;

LIST @WALMART_DB.BRONZE.WALMART_STAGE;

COPY INTO WALMART_DB.BRONZE.RAW_SALES
FROM @WALMART_DB.BRONZE.WALMART_STAGE/department.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT);

SELECT COUNT(*) FROM WALMART_DB.BRONZE.RAW_SALES;

SHOW TABLES IN SCHEMA WALMART_DB.BRONZE;

LIST @WALMART_DB.BRONZE.WALMART_STAGE;

COPY INTO WALMART_DB.BRONZE.RAW_STORES
FROM @WALMART_DB.BRONZE.WALMART_STAGE/stores.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT)
FORCE = TRUE;

CREATE OR REPLACE FILE FORMAT WALMART_DB.BRONZE.CSV_FORMAT
TYPE = CSV
FIELD_OPTIONALLY_ENCLOSED_BY = '"'
SKIP_HEADER = 1
NULL_IF = ('NULL', 'null', '', 'NA')
EMPTY_FIELD_AS_NULL = TRUE;


COPY INTO WALMART_DB.BRONZE.RAW_MACRO_DATA
FROM @WALMART_DB.BRONZE.WALMART_STAGE/fact.csv
FILE_FORMAT = (FORMAT_NAME = WALMART_DB.BRONZE.CSV_FORMAT)
FORCE = TRUE;

SELECT COUNT(*) FROM WALMART_DB.BRONZE.RAW_SALES;
SELECT COUNT(*) FROM WALMART_DB.BRONZE.RAW_STORES;
SELECT COUNT(*) FROM WALMART_DB.BRONZE.RAW_MACRO_DATA;
