CREATE OR REPLACE VIEW WALMART_DB.MARTS.WALMART_REPORTING AS
SELECT
    f.STORE_ID,
    f.DEPT_ID,
    d.STORE_DATE,
    d.IS_HOLIDAY,
    s.STORE_TYPE,
    s.STORE_SIZE,
    f.STORE_WEEKLY_SALES,
    f.FUEL_PRICE,
    f.STORE_TEMPERATURE,
    f.UNEMPLOYEMENT,
    f.CPI,
    f.MARKDOWN1,
    f.MARKDOWN2,
    f.MARKDOWN3,
    f.MARKDOWN4,
    f.MARKDOWN5
FROM WALMART_DB.MARTS.WALMART_FACT_TABLE f
LEFT JOIN WALMART_DB.MARTS.WALMART_DATE_DIM d
    ON f.DATE_ID = d.DATE_ID
LEFT JOIN WALMART_DB.MARTS.WALMART_STORE_DIM s
    ON f.STORE_ID = s.STORE_ID
   AND f.DEPT_ID = s.DEPT_ID;
