CREATE OR REPLACE STAGE WALMART_DB.BRONZE.WALMART_STAGE
URL = 's3://<S3_BUCKET_NAME>'
CREDENTIALS = (
  AWS_KEY_ID = '<AWS_KEY_ID>'
  AWS_SECRET_KEY = '<AWS_SECRET_KEY>'
)
FILE_FORMAT = WALMART_DB.BRONZE.CSV_FORMAT;
