SHOW STAGES IN SCHEMA WALMART_DB.BRONZE;

LIST @WALMART_DB.BRONZE.WALMART_STAGE;

SHOW TABLES IN SCHEMA WALMART_DB.BRONZE;

SELECT COUNT(*) AS RAW_SALES_COUNT
FROM WALMART_DB.BRONZE.RAW_SALES;

SELECT COUNT(*) AS RAW_STORES_COUNT
FROM WALMART_DB.BRONZE.RAW_STORES;

SELECT COUNT(*) AS RAW_MACRO_DATA_COUNT
FROM WALMART_DB.BRONZE.RAW_MACRO_DATA;

SHOW TABLES IN SCHEMA WALMART_DB.MARTS;

SELECT
    MIN(STORE_WEEKLY_SALES) AS MIN_WEEKLY_SALES,
    MAX(STORE_WEEKLY_SALES) AS MAX_WEEKLY_SALES,
    AVG(STORE_WEEKLY_SALES) AS AVG_WEEKLY_SALES
FROM WALMART_DB.MARTS.WALMART_FACT_TABLE;
